const activities=[
{id:1,date:'08-21 — 08-23（窗口前）',sort:'2025-08-21',title:'首届 Fotona Weekend Central America',type:'自办活动 / 区域峰会',group:'owned',place:'哥斯达黎加 Playa Herradura',venue:'Hotel Marriott Resort Los Sueños',purpose:'拉美区域自有活动 IP 落地，为拉美市场建立年度社群节点。',desc:'首次举办中美洲 Fotona Weekend，面向区域医生与伙伴开展临床教育与品牌活动。',data:'120 名医疗专业人士（美学/皮肤科/妇科）；12 位讲者：哥斯达黎加本土 Dr. Roberto Valdivia、Dr. Luis Diego Carazo、Dr. Ana Lucía Pineda、Dr. Carlos Arguedas、Dr. Carlos Bravo + 国际 Dr. Leonardo Marini、Dr. Adrian Gaspar、Dr. Jorge Baños、Dr. Julio Vélez 等；议程覆盖 StarWalker MaQX、Dynamis MAX、HoneyComb Lift、Micro Laser Coring、SuperSMOOTH 等；合作伙伴 G&G Medical Solutions（官方新闻 9766）。',audience:'中美洲医生、诊所与区域伙伴',result:'120 人、12 位讲者、Keynote+讲座+互动圆桌，官方新闻确认举办。',focus:'区域小型活动 IP 是否可持续复制到其他新兴市场。',products:'StarWalker MaQX · Dynamis MAX · HoneyComb Lift',source:'https://www.fotona.com/en/news/9766/',confidence:'A · 官网新闻（人数/讲者可核）',scale:'拉美区域活动'},
{id:2,date:'09-04 — 09-06',sort:'2025-09-04',title:'2025 Fotona Super Symposium',type:'自办活动 / 全球旗舰峰会',group:'owned',place:'美国德州 Irving',venue:'Irving Convention Center',purpose:'美国年度旗舰学术活动，承载高层发声、行业观点与客户关系。',desc:'近 500 名全球参会者；新 CEO Jeff Duchemin 首秀；Google 的 Lauren Abney 主讲 AI 医疗；1960s 主题晚宴。',data:'近 500 人参会（官方新闻 9778）；议程主题含 NaseLase/NightLase（睡眠与气道）、Fotona4D、激光再生、StarWalker 光声焕肤、StarFormer 磁疗；完整讲者名单与票价未公开（2025 活动页已被 2026 版覆盖）。',audience:'美国及全球医生、诊所经营者与伙伴',result:'近 500 人参会；CEO 首秀 + 跨界嘉宾 + 主题社交活动。',focus:'旗舰活动同时承担战略发布、客户关系和品牌温度三层功能。',products:'Jeff Duchemin · Lauren Abney (Google)',source:'https://www.fotona.com/en/news/9778/',confidence:'A · 官网新闻（2025-09-09）',scale:'全球旗舰峰会'},
{id:3,date:'09-13（新闻 09-15）',sort:'2025-09-13',title:'LA&HA 摩洛哥妇科培训项目',type:'教育培训 / 培训中心',group:'education',place:'摩洛哥',venue:'LA&HA 培训网络',purpose:'在摩洛哥新设妇科专项培训，扩张区域教育与获客网络。',desc:'LA&HA 学术网络在摩洛哥落地妇科培训项目。',data:'近 40 名妇科医生、3 场 hands-on 工作坊；主讲 Dr. Ivan Fistonić，本地讲者 Dr. Siham Kandri、Dr. Younes Benfdil、Dr. Naima Sedrati；内容含 SMOOTH 非侵入妇科术式、性功能、美学妇科、瘢痕与 HITS 磁技术；同场平行美学项目 70 人、5 场工作坊（Dr. Nicolas Rygaloff、Dr. Ashraf Badawi）；会前另有 5 场 1-on-1 EndoTight 手术工作坊（Dr. Montserrat Ponga Manso）（新闻 9779）。',audience:'区域妇科医生与诊所',result:'近 40 名妇科医生 + 70 人美学项目 + 5 场手术工作坊。',focus:'妇科是 Fotona 差异化科室，培训网络跟着适应症扩张。',products:'Fotona SMOOTH · HITS · 妇科治疗线',source:'https://www.fotona.com/en/news/9779/',confidence:'A · 官网新闻（人数/讲者可核）',scale:'区域培训中心'},
{id:4,date:'10-16',sort:'2025-10-16',title:'LA&HA 乌兹别克斯坦培训中心落成',type:'教育培训 / 培训中心',group:'education',place:'乌兹别克斯坦塔什干',venue:'LA&HA 培训中心',purpose:'中亚首个培训中心，服务当地医生教育与渠道培训。',desc:'LA&HA 乌兹别克斯坦培训中心正式落成，扩充全球培训网络。',data:'设施预计 2026 年初开课，覆盖皮肤科与妇科；合作方 Mr. Arsen Djanov（Aesthetic Systems LLC）、Mrs. Indira Salamova（Medestetica LLC，覆盖乌兹别克斯坦与吉尔吉斯斯坦）；已认证 3 位区域培训师：Dr. Aksana Zhumashalieva（皮肤科）、Dr. Nodira Yuldasheva（ENT）、Dr. Aleksandra Koteniatkina（妇产科）（新闻 9862）。',audience:'中亚医生、临床人员与渠道伙伴',result:'全年累计新增 3 个培训中心；中亚培训网络落地。',focus:'培训中心是"装机后持续触达"的物理载体。',products:'LA&HA 培训网络',source:'https://www.fotona.com/en/news/9862/',confidence:'A · 官网新闻（培训师名单可核）',scale:'区域培训中心'},
{id:5,date:'10 月（新闻 11-03）',sort:'2025-10-15',title:'第 11 届 Fotona APAC 会议',type:'自办活动 / 区域峰会',group:'owned',place:'墨尔本，澳大利亚',venue:'APAC 会议会场',purpose:'亚太年度旗舰，连接区域医生、伙伴与新品节奏。',desc:'CEO 开幕；纪念澳洲分销伙伴 Paul Baltas；宣布墨尔本新 LA&HA 培训中心；官宣 2026 届移师雅加达。',data:'CEO Jeff Duchemin 开幕致辞；追思已故澳洲分销商 Innovative Medical Technologies 前 CEO Paul Baltas；Day 2 牙科议程（NightLase、光生物调节、口腔手术、SkyPulse/LightWalker 实操）+ 美学议程（HAIRestart、亚洲皮肤护理、黄褐斑）；Gala Dinner + 鸡尾酒会；会后在墨尔本新培训中心开工作坊；下届 2026 雅加达（新闻 9839）。参会总人数未公开。',audience:'亚太医生、分销伙伴与诊所客户',result:'完成年度会议、伙伴纪念、培训中心官宣与下届预告。',focus:'区域会议同时承担伙伴关系维护与下届营销钩子。',products:'LightWalker · NightLase · HAIRestart · Paul Baltas',source:'https://www.fotona.com/en/news/9839/',confidence:'A · 官网新闻（议程可核，人数未公开）',scale:'亚太旗舰会议'},
{id:6,date:'12-29',sort:'2025-12-29',title:'4 项新研究支持 SMOOTH 治疗压力性尿失禁',type:'学术 PR / 临床证据',group:'pr',place:'全球',venue:'官网新闻中心',purpose:'用新临床证据为妇科市场准入与合规宣传提供弹药。',desc:'发布 4 项新研究，支持 SMOOTH® 技术在压力性尿失禁治疗中的价值。',data:'① Wang et al. 多中心前瞻随机假对照：126 例轻中度 SUI，3 次治疗后 3 个月成功率 71.4%（约为假治疗组 2 倍，DOI 10.1007/s10103-025-04400-3）；② Phillips et al. 多中心 RCT：6 个月治愈率 62.7% vs 18.2%（DOI 10.1111/1471-0528.70080）；③ Erel et al. 尿道内 vs 联合方案，随访 12 个月（DOI 10.1007/s10103-025-04691-6）；④ Pancholia et al. 患者报告结局，2 个月改善、9 个月持续（DOI 10.1155/aiu/1255593）（新闻 9918）。',audience:'妇科医生、医疗决策者与行业媒体',result:'4 项研究携完整 DOI 发布，进入文献营销资产库。',focus:'学术 PR 是器械进入严肃医疗场景的信任基础设施。',products:'SMOOTH® · IncontiLase · 妇科治疗线',source:'https://www.fotona.com/en/news/9918/',confidence:'A · 官网新闻（DOI 可核）',scale:'全球学术 PR'},
{id:7,date:'02-03',sort:'2026-02-03',title:'IMCAS 2026："Glow Up" 概念全球首发',type:'展会 / 学术会议 / 概念发布',group:'exhibition',place:'巴黎，法国',venue:'IMCAS 会场 · Industry Symposium',purpose:'在全球最大医美大会上首发新 Campaign 概念，最大化曝光与权威背书。',desc:'IMCAS 2026 破纪录 21,764 人参会；Fotona Industry Symposium 座无虚席；Live Demo + VIP Party。',data:'IMCAS 2026 总参会 21,764 人（Fotona 官方口径，破纪录；第三方交叉口径为 2 万+/400+ 展商）；Symposium 讲者：Prof. Leonardo Marini & Dr. Susanna Marini《Combination Laser Treatments for Every Age》、Dr. Lucas Chia《Why Choose StarWalker PICO Pro?》、Dr. Tania Phillips《Why Choose Dynamis Max?》；On-Site Meetings 12 位专家：Dr. Nicolas Rygaloff、Dr. Tania Phillips、Dr. Barry Dekeyser、Dr. Susanna Marini、Dr. Carlos Gaspar、Dr. Naci Celik、Dr. Ivana Tancer Bogataj、Prof. Ashraf Badawi、Prof. Leonardo Marini、Dr. Lucas Chia、Dr. Xianglei Wu、Dr. Adrian Gaspar；Live Demo：Dr. Nicolas Rygaloff（Fotona4GLOW + L-Runner）；VIP 活动官方名 Fotona Laser Experts VIP Dinner & Party（新闻 9947）。',audience:'全球皮肤科与医美医生、诊所、媒体与经销商',result:'21,764 人大会 + Symposium 满场 + 12 位专家现场会 + Live Demo + VIP Dinner。',focus:'把新品概念首发放在最大展会，一次完成曝光、背书和线索。',products:'Glow Up 概念 · Dynamis + StarWalker',source:'https://www.fotona.com/en/news/9947/',confidence:'A · 官网新闻（讲者名单可核）',scale:'全球大型展会'},
{id:8,date:'02-04 起',sort:'2026-02-04',title:'"Glow Up with Fotona" Campaign 上线',type:'命名 Campaign / 治疗产品化',group:'campaign',place:'全球',venue:'Campaign 落地页 + 官网',purpose:'把 Fotona4GLOW™ 四步协议打包成可售卖的治疗概念，反向拉动双平台销售。',desc:'Fotona4GLOW™ 四步协议（Toning→FRAC3®→PIANO→FracTAT®），多语言落地页全球上线。',data:'四步确认：Toning（StarWalker）→ FRAC3（Dynamis）→ PIANO（Dynamis）→ FracTAT（StarWalker）；KOL：Dr. Lucas Liang-Choong Chia 医生证言，Prof. Leonardo Marini & Dr. Susanna Marini 4/8 Live Expert Talk 主讲；campaign 页引用 9 篇临床文献；产品数据：治疗 ≤30 分钟、适用所有 Fitzpatrick 肤色；落地页语言选择器现示 5 种（EN/ES/DE/FR/IT，未找到"8 语言"公开依据）。',audience:'诊所经营者、医生与患者教育受众',result:'多语言落地页 + KOL 直播 + 9 篇文献支撑全球上线。',focus:'"不卖机器、卖可命名的治疗方案"是 Fotona 的核心打法。',products:'Fotona4GLOW™ · Dynamis® + StarWalker®',source:'https://www.fotona.com/en/campaigns/9917/glow-up-with-fotona/',confidence:'A · Campaign 官网（KOL/文献可核）',scale:'全球命名 Campaign'},
{id:9,date:'03-05 起',sort:'2026-03-05',title:'FotonaSMILE Campaign 上线',type:'命名 Campaign / KOL 学术',group:'campaign',place:'全球',venue:'Campaign 落地页 + Webinar + Workshop',purpose:'牙科线治疗产品化：用"7 Secrets"框架包装 LightWalker 术式组合。',desc:'"7 Secrets of the FotonaSMILE"框架 + 5 位 KOL "Luminaries" + 双周 Webinar + 5.11 直播 + 6.15 线下 Workshop。',data:'5 位 Luminaries：Dr. Linhlan Nguyen（LipLase & TouchWhite）、Dr. Alexandra Marques（Crown Lengthening & Lesions）、Dr. Rita El Feghali（Debonding & Depigmentation）、Dr. Hui Jing Phang（SmoothLiftin & LipLase）、Dr. Grisel Martos（商业视角）；5.11 Live Expert Talk；6.15 Workshop 于 Ljubljana LA&HA Institute（Dr. Linhlan Nguyen 主持，覆盖 7 个协议 + 真人演示）；LightWalker II "80+ 预设应用"；落地页语言 6 种（EN/ES/FR/IT/PT/PL）。',audience:'牙科医生、诊所与牙科渠道',result:'5 位 KOL 双周 Webinar 日历 + 直播 + 卢布尔雅那线下 Workshop。',focus:'Campaign 标配"KOL+内容日历+线下承接"三段结构。',products:'LightWalker® · 5 位 Luminaries KOL',source:'https://www.fotona.com/en/campaigns/9943/the-7-secrets-of-the-fotonasmile/',confidence:'A · Campaign 官网（KOL/议程可核）',scale:'全球命名 Campaign'},
{id:10,date:'03-27',sort:'2026-03-27',title:'AMWC 2026 双奖',type:'奖项 PR / 行业背书',group:'pr',place:'摩纳哥',venue:'AMWC 颁奖',purpose:'行业奖项为设备与技术建立第三方权威背书，并转化为新闻与社媒内容。',desc:'StarWalker® PICO Pro 获"最佳激光 / 光 / 能量设备"奖；Dr. Susanna Marini 凭 Fotona 点阵技术获"最佳能量治疗"奖。',data:'奖项全称：Best Laser, Light & Energy-Based Device（StarWalker PICO Pro）与 Best Energy-Based Treatment（Dr. Susanna Marini，论文《Thermo-Fractional Laser-Assisted Photodynamic Therapy for Facial Rejuvenation》）；AMWC 2026 大会规模：17,688 与会者、350 家参展公司、141 个国家（主办方 Post-Show Report）。',audience:'行业媒体、医生与潜在采购者',result:'设备 + 治疗双奖，官方新闻稿全球传播。',focus:'奖项是低成本高信任的 B2B 传播杠杆。',products:'StarWalker® PICO Pro · Dr. Susanna Marini',source:'https://www.fotona.com/en/news/10010/',confidence:'A · 官网新闻 + AMWC Post-Show Report',scale:'全球奖项 PR'},
{id:11,date:'06 月（LA&HA 06-12~13）',sort:'2026-06-10',title:'第 23 届 IFW & 第 16 届 LA&HA Symposium',type:'自办活动 / 全球学术旗舰',group:'owned',place:'斯洛文尼亚 Portorož',venue:'IFW & LA&HA 会场',purpose:'欧洲总部年度学术旗舰，覆盖牙科、美学、妇科三大学科。',desc:'800+ 参会者、80+ 专家讲座、Best Lecture Awards（牙科 / 美学 / 妇科各 1 名）。',data:'800+ 参会、80+ 讲座；Best Lecture Awards 获奖者：Dr. Fernando Duarte（牙科，葡萄牙）、Dr. Lucas Chia（美学/皮肤科，马来西亚）、Dr. Jorge Gaviria（妇科，美国）；LA&HA Symposium 官方日期 2026-06-12~13；对照上届 2025 为 700+ 参会、100+ 讲师（新闻 9491）。完整讲者名单未公开。',audience:'全球牙科、美学、妇科医生与专家',result:'800+ 参会、80+ 讲座、3 项最佳讲座奖（获奖人已公布）。',focus:'三学科并行的学术旗舰是 Fotona 差异化产品矩阵的展示场。',products:'全产品线 · LA&HA 学术网络',source:'https://www.fotona.com/en/news/10045/',confidence:'A · 官网新闻 + LA&HA 官网',scale:'全球学术旗舰'},
{id:12,date:'09-10 — 09-12',sort:'2026-09-10',title:'2026 Fotona Super Symposium',type:'自办活动 / 全球旗舰峰会',group:'owned',place:'美国德州 Irving',venue:'ICC + Westin Las Colinas',purpose:'2026 美国旗舰，延续年度节奏并承接新品与课程发布。',desc:'牙科 / Wellness / 美学与皮肤科三大分会场、30+ 讲者、3 天议程、Gala Dinner。',data:'官网已公布 39 位讲者，含 Dr. Scott Benjamin、Dr. Lucas Chia、Dr. Mohamed Fayad、Dr. Jorge Gaviria、Dr. Robert Weiss、Dr. Azza Halim、Dr. Linhlan Nguyen 等；议程：9/10 全天入门课程（仅限预注册）+ Welcome Reception，9/11 全体大会 + Keynote + 分会场 + Gala Dinner，9/12 分会场 + Farewell Dinner；报名经 Eventbrite（票价未公开）。',audience:'美国医生、诊所与伙伴',result:'39 位讲者、三天议程、三分会场 + Gala。',focus:'旗舰活动连续举办形成年度期待与复购触点。',products:'全产品线',source:'https://www.fotonasupersymposium.com/',confidence:'A · 活动官网（讲者名单可核）',scale:'全球旗舰峰会'},
{id:13,date:'09-01（生效 08-24）',sort:'2026-09-01',title:'任命 Alasdair Owen 为首席产品官',type:'组织 PR / 战略信号',group:'pr',place:'全球',venue:'官方新闻 + PR Newswire',purpose:'以高管任命传递"进入下一增长阶段"的战略信号。',desc:'任命 MedTech 老将 Alasdair Owen 为首席产品官，统管全球 R&D、产品组合战略与创新。',data:'任职 2026-08-24 生效，向 CEO Jeff Duchemin 直接汇报；自 Intuitive 加入，曾任欧洲产品组合营销负责人（da Vinci 平台与机器人辅助外科产品线）；PR Newswire 同步披露公司规模：60+ 年历史、300+ 专利、60,000+ 客户、100+ 国家。',audience:'行业、投资者与渠道',result:'官方新闻 + PR Newswire 全球通稿。',focus:'产品官任命暗示产品线扩张节奏，值得持续跟踪。',products:'Alasdair Owen · Jeff Duchemin',source:'https://www.fotona.com/en/news/10149/',confidence:'A · 官网新闻 + PR Newswire',scale:'企业传播'}
];

const labels={exhibition:'展会 / 会议',owned:'自办活动',education:'教育培训',campaign:'命名 Campaign',pr:'品牌 PR'};
let active='all',ascending=true;
const grid=document.querySelector('#activity-grid'),search=document.querySelector('#search'),dialog=document.querySelector('#dialog');
function render(){
 const q=search.value.trim().toLowerCase();
 const list=activities.filter(a=>(active==='all'||a.group===active)&&[a.title,a.place,a.products,a.purpose,a.audience].join(' ').toLowerCase().includes(q)).sort((a,b)=>(ascending?1:-1)*a.sort.localeCompare(b.sort));
 grid.innerHTML=list.map(a=>`<article class="activity-card" tabindex="0" data-id="${a.id}"><div class="card-image placeholder" data-label="FOTONA ${a.date.split(' ')[0]}"><span class="badge">${labels[a.group]}</span><span class="scale-badge">${a.scale}</span></div><div class="card-body"><div class="date-place"><span>${a.date}</span><span>${a.place}</span></div><h3>${a.title}</h3><dl class="facts"><div><dt>活动说明</dt><dd>${a.purpose}</dd></div><div><dt>Fotona 动作</dt><dd>${a.desc}</dd></div>${a.data?`<div class="focus"><dt>数据支撑</dt><dd>${a.data}</dd></div>`:''}<div><dt>主要受众</dt><dd>${a.audience}</dd></div><div><dt>公开结果</dt><dd>${a.result}</dd></div><div class="focus"><dt>关注点</dt><dd>${a.focus}</dd></div></dl><div class="card-foot"><span class="products">${a.products}</span><span class="open-icon">↗</span></div></div></article>`).join('');
 document.querySelector('#result-count').textContent=`${list.length} 条记录`;document.querySelector('#empty').style.display=list.length?'none':'block';
}
document.querySelectorAll('.filters button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelector('.filters .active').classList.remove('active');btn.classList.add('active');active=btn.dataset.filter;render()}));
search.addEventListener('input',render);document.querySelector('#sort').addEventListener('click',e=>{ascending=!ascending;e.currentTarget.textContent=`日期：${ascending?'从早到晚':'从晚到早'} ↕`;render()});
function openDetail(id){const a=activities.find(x=>x.id===id);document.querySelector('#dialog-content').innerHTML=`<div class="dialog-inner"><div class="dialog-media"></div><div class="dialog-body"><span class="type">${labels[a.group]} · ${a.type}</span><h2>${a.title}</h2><div class="dialog-meta"><div><span>时间</span>${a.date}</div><div><span>地点 / 市场</span>${a.place}</div><div><span>会场</span>${a.venue}</div><div><span>规模</span>${a.scale}</div></div><div class="dialog-detail"><div><span>这个活动是做什么的</span><p>${a.purpose}</p></div><div><span>Fotona 开展的内容</span><p>${a.desc}</p></div>${a.data?`<div class="focus"><span>数据支撑</span><p>${a.data}</p></div>`:''}<div><span>受众</span><p>${a.audience}</p></div><div><span>公开结果</span><p>${a.result}</p></div><div class="focus"><span>竞争关注点</span><p>${a.focus}</p></div></div><div class="dialog-products"><strong>重点产品 / 人物</strong><br>${a.products}</div><a class="dialog-source" href="${a.source}" target="_blank" rel="noreferrer">查看来源 <span>↗</span></a><p class="confidence">${a.confidence}</p></div></div>`;dialog.showModal()}
grid.addEventListener('click',e=>{const card=e.target.closest('.activity-card');if(card)openDetail(Number(card.dataset.id))});grid.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('.activity-card'))openDetail(Number(e.target.dataset.id))});document.querySelector('.close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});render();
